#!/usr/bin/env bash

declare -x WATCHTOWER_CLEANUP
: "${WATCHTOWER_CLEANUP:="false"}"

declare -x WATCHTOWER_DEBUG
: "${WATCHTOWER_DEBUG:="false"}"

declare -x WATCHTOWER_ENABLE_LIFECYCLE_HOOKS
: "${WATCHTOWER_ENABLE_LIFECYCLE_HOOKS:="false"}"

declare -x WATCHTOWER_HOST
: "${WATCHTOWER_HOST:="unix:///var/run/docker.sock"}"

declare -x WATCHTOWER_HTTP_API_METRICS
: "${WATCHTOWER_HTTP_API_METRICS:="false"}"

declare -x WATCHTOWER_HTTP_API_PERIODIC_POLLS
: "${WATCHTOWER_HTTP_API_PERIODIC_POLLS:="false"}"

declare -x WATCHTOWER_HTTP_API_TOKEN
: "${WATCHTOWER_HTTP_API_TOKEN:=""}"

declare -x WATCHTOWER_HTTP_API_UPDATE
: "${WATCHTOWER_HTTP_API_UPDATE:="false"}"

declare -x WATCHTOWER_INCLUDE_RESTARTING
: "${WATCHTOWER_INCLUDE_RESTARTING:="false"}"

declare -x WATCHTOWER_INCLUDE_STOPPED
: "${WATCHTOWER_INCLUDE_STOPPED:="false"}"

declare -x WATCHTOWER_INTERVAL
: "${WATCHTOWER_INTERVAL:="300"}"

declare -x WATCHTOWER_LABEL_ENABLE
: "${WATCHTOWER_LABEL_ENABLE:="false"}"

declare -x WATCHTOWER_MONITOR_ONLY
: "${WATCHTOWER_MONITOR_ONLY:="false"}"

declare -x WATCHTOWER_NO_COLOR
: "${WATCHTOWER_NO_COLOR:="false"}"

declare -x WATCHTOWER_NO_PULL
: "${WATCHTOWER_NO_PULL:="false"}"

declare -x WATCHTOWER_NO_RESTART
: "${WATCHTOWER_NO_RESTART:="false"}"

declare -x WATCHTOWER_NO_STARTUP_MESSAGE
: "${WATCHTOWER_NO_STARTUP_MESSAGE:="false"}"

declare -x WATCHTOWER_REMOVE_VOLUMES
: "${WATCHTOWER_REMOVE_VOLUMES:="false"}"

declare -x WATCHTOWER_REVIVE_STOPPED
: "${WATCHTOWER_REVIVE_STOPPED:="false"}"

declare -x WATCHTOWER_ROLLING_RESTART
: "${WATCHTOWER_ROLLING_RESTART:="false"}"

declare -x WATCHTOWER_RUN_ONCE
: "${WATCHTOWER_RUN_ONCE:="false"}"

declare -x WATCHTOWER_SCHEDULE
: "${WATCHTOWER_SCHEDULE:=""}"

declare -x WATCHTOWER_SCOPE
: "${WATCHTOWER_SCOPE:=""}"

declare -x WATCHTOWER_STOP_TIMEOUT
: "${WATCHTOWER_STOP_TIMEOUT:=""}"

declare -x WATCHTOWER_TLS_VERIFY
: "${WATCHTOWER_TLS_VERIFY:="false"}"

declare -x WATCHTOWER_TRACE
: "${WATCHTOWER_TRACE:="false"}"

declare -x WATCHTOWER_WARN_ON_HEAD_FAILURE
: "${WATCHTOWER_WARN_ON_HEAD_FAILURE:=""}"

declare -x WATCHTOWER_OPTS
: "${WATCHTOWER_OPTS:=""}"

declare -x DOCKER_API_VERSION
: "${DOCKER_API_VERSION:="1.24"}"
