FROM ghcr.io/dockhippie/golang:1.23-amd64@sha256:ae113f11f31e5bc0986ac457fecad3220e8ad19c235a480227f2f0b6cccbc8b4 AS build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.5.3

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:834be7ffc1914f6bfec751411aa954efee570aaccaa7cfcf21b0e92e264701d7

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /
