FROM ghcr.io/dockhippie/golang:1.23-arm64@sha256:51ed486faeaa072af4492331506b20d1dc6db4753e201cfc6b949766540b1184 AS build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.5.3

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:a08ec5f5aaf68c73e1ae4d1cfe9949dccf9e3f0c49d8088a0f0c42491ef77cd3

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /
