FROM ghcr.io/dockhippie/golang:1.23-arm@sha256:19e0578e33086e02a4c49c8e6264a1138c4dd5e4c216d2fd3d31d15e00fa6aa4 AS build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.5.3

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:8253d93cf993bf7d69fcacebb3da4454d5b138325ddf51a0881df39b0df86007

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /
