FROM ghcr.io/dockhippie/golang:1.21-amd64@sha256:82c5210820472f64a5bee97e256ca6754e06ee064ba9bf1cbdee7673c11fea31 AS build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.5.3

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:61e25d53dee3df134ae5b2a09a0f17696c24dbd0404cca98a041cb7d7cc2d7b4

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /
