FROM ghcr.io/dockhippie/golang:1.23-arm64@sha256:ffd5cc823a04ad2c1bd74ae5c1bd21a9a7caca97b5f9a2b5e950a618bf077b44 AS build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.5.3

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:adc7e1ccbe6a6fccad0a1e713e098db3edb1947b9ec97f3f78f37faf849326d6

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /
