FROM webhippie/golang:1.10-arm64v8@sha256:283a0a9715d1c150980abec654794911fe2aacd8a5db57d0c758e05eafb0f708 as build

ENV WATCHTOWER_PATH github.com/v2tec/watchtower
ENV WATCHTOWER_REPO https://${WATCHTOWER_PATH}.git
ENV WATCHTOWER_BRANCH master

RUN git clone -b ${WATCHTOWER_BRANCH} ${WATCHTOWER_REPO} /srv/app/src/${WATCHTOWER_PATH} && \
  cd /srv/app/src/${WATCHTOWER_PATH} && \
  go get -u github.com/Masterminds/glide && \
  glide install --skip-test && \
  go install

FROM webhippie/alpine:latest-arm64v8@sha256:47921c78e4cb3dafe1338629eea137dd909882fb01e2583750e110ae4bdcc20b

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Watchtower" \
  org.label-schema.vcs-url="https://github.com/dockhippie/watchtower.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay ./overlay-arm64v8 /
