FROM webhippie/golang:1.17-arm64@sha256:d74d1c819b6f27798a47893e163f6070eca4ffafd06668ab5a6faf1feeb53739 as build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.4.0

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM webhippie/alpine:latest-arm64@sha256:d059dc58e0739aac431b71e85cde3fd0ebdafd6d57f51113647548c15eff5ea0

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /
