FROM webhippie/golang:1.12-arm64v8@sha256:ae9e601d88b1a1abe23a8dbc2a2e7e552bd303732aee78b61d9e3f9592445877 as build

ENV WATCHTOWER_PATH github.com/v2tec/watchtower
ENV WATCHTOWER_REPO https://${WATCHTOWER_PATH}.git
ENV WATCHTOWER_BRANCH master

RUN git clone -b ${WATCHTOWER_BRANCH} ${WATCHTOWER_REPO} /srv/app/src/${WATCHTOWER_PATH} && \
  cd /srv/app/src/${WATCHTOWER_PATH} && \
  go get -u github.com/Masterminds/glide && \
  glide install --skip-test && \
  go install

FROM webhippie/alpine:latest-arm64v8@sha256:2af125d3829f11d05c99396f5a29d5592f6d44fb37d9c384497fdd7beef62c5b

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Watchtower" \
  org.label-schema.vcs-url="https://github.com/dockhippie/watchtower.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay ./overlay-arm64v8 /
