FROM ghcr.io/dockhippie/golang:1.23-arm64@sha256:39f4cd73e8290638100eefe6477851084f59ae8802a8fdf44d5441847e077a0b AS build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.7.1

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:d7813fe27f3eeb726a418182751235f564ab8e965cc6e35d6f676fba29ee05bd

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /
