FROM webhippie/golang:1.16-arm@sha256:719c0e27a10377e9c36b332c9c658e3501619c9316c307c35055eaede6def80d as build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.3.0

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM webhippie/alpine:latest-arm@sha256:b08c54bfa168cfca29296b6fca34513c1e4866b2aa5052876600ad28acb87132

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /
