FROM webhippie/golang:1.18-amd64@sha256:9896fa1b19fdc40d454ad9531f5c05ca233d63825545cecb65274656192a6adb as build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.4.0

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM webhippie/alpine:latest-amd64@sha256:231fb42aee049af3fc8fa9317da2a6642703e3b410b068947995054b20658556

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /
