FROM webhippie/golang:1.12-arm32v6@sha256:c20d6d49a15ecc21acaafead81de2cf285660aced170ed4826f11392b0045eb7 as build

ENV WATCHTOWER_PATH github.com/v2tec/watchtower
ENV WATCHTOWER_REPO https://${WATCHTOWER_PATH}.git
ENV WATCHTOWER_BRANCH master

RUN git clone -b ${WATCHTOWER_BRANCH} ${WATCHTOWER_REPO} /srv/app/src/${WATCHTOWER_PATH} && \
  cd /srv/app/src/${WATCHTOWER_PATH} && \
  go get -u github.com/Masterminds/glide && \
  glide install --skip-test && \
  go install

FROM webhippie/alpine:latest-arm32v6@sha256:e974574e5a59c39564f075610a5e157c9053ed12d809d1c20d724687b2975311

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Watchtower" \
  org.label-schema.vcs-url="https://github.com/dockhippie/watchtower.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay ./overlay-arm32v6 /
