FROM webhippie/golang:1.16-arm64@sha256:72153a5b2c3d2796f96de3fb01f3f9b8c16dfadb2195642ef2bef114bd501ce3 as build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.3.0

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM webhippie/alpine:latest-arm64@sha256:304bc1d52d7acd7621eaa61b3089fe7db2122663d83c0c7095df146a400d693e

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /
