FROM ghcr.io/dockhippie/golang:1.20-amd64@sha256:25669de244089c5014e296c536b2bdb9eddba6b62bc91cbfeb1e60066ea81c6e

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.4.0

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:0f01e71f5f6079c7cdba767907024e3aa3b20e2ae6c426dfe18a4f497f57af3b

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /
