FROM ghcr.io/dockhippie/golang:1.23-amd64@sha256:370a1735955ffc1a61f77f6c6ae3f3eb3c4ed15047f62d53353a257f29a7363f AS build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.4.0

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:93493def75ab3695096b69762ca1afe1be11651bad4734e5608a9647e0a55fe1

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /
