FROM ghcr.io/dockhippie/golang:1.25-arm@sha256:e6ea72a314733ba80fb98032e3151153afb5fb87f77efdf26b257cb058e84d9e AS build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.6.0

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:19e1a7f3699b66f9e99a2ce7c0cf958882ae9527c1a21965ab7e2cce5282f41b

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /

RUN find /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/container && \
  chmod +x /usr/bin/container /etc/entrypoint.d/*.sh
