FROM ghcr.io/dockhippie/golang:1.27-amd64@sha256:67570f266a13610b94e4bfc600df713c85e60c199d4611bc659d5817916092aa AS build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.6.0

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:521c63eb29b1cc282ec04e4286d00d4f6f71c190bca72fc5d2d4fd0c4df8bdf9

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /

RUN find /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/container && \
  chmod +x /usr/bin/container /etc/entrypoint.d/*.sh
