FROM ghcr.io/dockhippie/golang:1.25-amd64@sha256:25106780f311a95646a35b4a4a21edabf30da9f852bb448bb3e9e75523d731e3 AS build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.6.0

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:8b11cb7689488ea128269fc7e7e57d0b493c6108baf8dfd02e793541fadf1d3f

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /

RUN find /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/container && \
  chmod +x /usr/bin/container /etc/entrypoint.d/*.sh
