#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

STARTCMD="/usr/bin/watchtower"

[[ "${WATCHTOWER_DEBUG}" == "true" || "${WATCHTOWER_DEBUG}" == "1" ]] && STARTCMD="${STARTCMD} --debug"
[[ "${WATCHTOWER_NO_RESTART}" == "true" || "${WATCHTOWER_NO_RESTART}" == "1" ]] && STARTCMD="${STARTCMD} --no-restart"
[[ "${WATCHTOWER_NO_PULL}" == "true" || "${WATCHTOWER_NO_PULL}" == "1" ]] && STARTCMD="${STARTCMD} --no-pull"
[[ "${WATCHTOWER_CLEANUP}" == "true" || "${WATCHTOWER_CLEANUP}" == "1" ]] && STARTCMD="${STARTCMD} --cleanup"
[[ "${WATCHTOWER_TLS_VERIFY}" == "true" || "${WATCHTOWER_TLS_VERIFY}" == "1" ]] && STARTCMD="${STARTCMD} --tlsverify"
[[ -n "${WATCHTOWER_TLS_VERIFY}" ]] && STARTCMD="${STARTCMD} --host=${WATCHTOWER_HOST}"
[[ -n "${WATCHTOWER_INTERVAL}" ]] && STARTCMD="${STARTCMD} --interval=${WATCHTOWER_INTERVAL}"
[[ -n "${WATCHTOWER_SCHEDULE}" ]] && STARTCMD="${STARTCMD} --schedule=${WATCHTOWER_SCHEDULE}"
[[ -n "${WATCHTOWER_OPTS}" ]] && STARTCMD="${STARTCMD} ${WATCHTOWER_OPTS}"

exec ${STARTCMD}
