#!/bin/bash

declare -x WATCHTOWER_TLS_CA
declare -x WATCHTOWER_TLS_KEY
declare -x WATCHTOWER_TLS_CERT

if [ -n "${WATCHTOWER_TLS_CA}" ]
then
  if [ ! -f "${WATCHTOWER_TLS_CA}" ]
  then
    echo -e "${WATCHTOWER_TLS_CA}" >| /tmp/ca.crt
    WATCHTOWER_TLS_CA="/tmp/ca.crt"
  fi
fi

if [ -n "${WATCHTOWER_TLS_KEY}" ]
then
  if [ ! -f "${WATCHTOWER_TLS_KEY}" ]
  then
    echo -e "${WATCHTOWER_TLS_KEY}" >| /tmp/etcd.crt
    WATCHTOWER_TLS_KEY="/tmp/docker.crt"
  fi
fi

if [ -n "${WATCHTOWER_TLS_CERT}" ]
then
  if [ ! -f "${WATCHTOWER_TLS_CERT}" ]
  then
    echo -e "${WATCHTOWER_TLS_CERT}" >| /tmp/etcd.key
    WATCHTOWER_TLS_CERT="/tmp/docker.key"
  fi
fi
