FROM ghcr.io/dockhippie/golang:1.25-amd64@sha256:25e988b9bef1c2b8a473e59915996b6e332b0dbe119b256b546eb5595d7a3e47 AS build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.7.1

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:5b037c077d4ba74ae7da3a97e0f4a5caff892dfae63bc2ca2f9053a46f6c40d7

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /
