FROM ghcr.io/dockhippie/golang:1.25-arm@sha256:69e5a37b6b7a8e4d2f51cea02748a659bdaf5b60adbdabd0b274b5fb801e39f4 AS build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.7.1

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:0564e2254cfceb37208430c87eea88ea4945f668ce5620a672cbae07b051c5b9

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /

RUN find /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/container && \
  chmod +x /usr/bin/container /etc/entrypoint.d/*.sh
