FROM ghcr.io/dockhippie/golang:1.25-arm@sha256:fd1e016fd8d9e18e94c4586476f3a23f2956acf88a18d6626695634633a183c9 AS build

# renovate: datasource=github-tags depName=containrrr/watchtower
ENV WATCHTOWER_VERSION=v1.7.1

RUN git clone -b ${WATCHTOWER_VERSION} https://github.com/containrrr/watchtower.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:b390a7b6e27e6915ddc2c1391872ba5dcc4a8bd015ebb217e2ecda063f383b4f

WORKDIR /root
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/watchtower /usr/bin/watchtower
COPY ./overlay /
